import Image from 'next/image'

export const CLASSES_NAMES: { [k: string]: string } = {
    '1': 'barbarian',
    '2': 'bard',
    '3': 'cleric',
    '4': 'druid',
    '5': 'fighter',
    '6': 'monk',
    '7': 'paladin',
    '8': 'ranger',
    '9': 'rogue',
    '10': 'sorcerer',
    '11': 'wizard',
}

export const CLASSES_IDS: { [k: string]: number } = {
    'barbarian': 1,
    'bard': 2,
    'cleric': 3,
    'druid': 4,
    'fighter': 5,
    'monk': 6,
    'paladin': 7,
    'ranger': 8,
    'rogue': 9,
    'sorcerer': 10,
    'wizard': 11,
}

export const CLASSES_IMAGES: { [k: string]: JSX.Element } = {
    '1': <Image src="/img/classes/full/barbarian.png" width={85} height={175} alt={'barbarian'} />,
    '2': <Image src="/img/classes/full/bard.png" width={80} height={175} alt={'bard'} />,
    '3': <Image src="/img/classes/full/cleric.png" width={115} height={175} alt={'cleric'} />,
    '4': <Image src="/img/classes/full/druid.png" width={70} height={175} alt={'druid'} />,
    '5': <Image src="/img/classes/full/fighter.png" width={65} height={175} alt={'fighter'} />,
    '6': <Image src="/img/classes/full/monk.png" width={85} height={175} alt={'monk'} />,
    '7': <Image src="/img/classes/full/paladin.png" width={75} height={175} alt={'paladin'} />,
    '8': <Image src="/img/classes/full/ranger.png" width={87} height={175} alt={'ranger'} />,
    '9': <Image src="/img/classes/full/rogue.png" width={90} height={175} alt={'rogue'} />,
    '10': <Image src="/img/classes/full/sorcerer.png" width={100} height={175} alt={'sorcerer'} />,
    '11': <Image src="/img/classes/full/wizard.png" width={75} height={175} alt={'wizard'} />,
}

export const CLASSES_HEADS: { [k: string]: JSX.Element } = {
    '1': <Image src="/img/classes/heads/barbarian.png" width={50} height={50} alt={'barbarian'} />,
    '2': <Image src="/img/classes/heads/bard.png" width={50} height={50} alt={'bard'} />,
    '3': <Image src="/img/classes/heads/cleric.png" width={50} height={50} alt={'cleric'} />,
    '4': <Image src="/img/classes/heads/druid.png" width={50} height={50} alt={'druid'} />,
    '5': <Image src="/img/classes/heads/fighter.png" width={50} height={50} alt={'fighter'} />,
    '6': <Image src="/img/classes/heads/monk.png" width={50} height={50} alt={'monk'} />,
    '7': <Image src="/img/classes/heads/paladin.png" width={50} height={50} alt={'paladin'} />,
    '8': <Image src="/img/classes/heads/ranger.png" width={50} height={50} alt={'ranger'} />,
    '9': <Image src="/img/classes/heads/rogue.png" width={50} height={50} alt={'rogue'} />,
    '10': <Image src="/img/classes/heads/sorcerer.png" width={50} height={50} alt={'sorcerer'} />,
    '11': <Image src="/img/classes/heads/wizard.png" width={50} height={50} alt={'wizard'} />,
}

export const CLASS_SKILLS: { [k: string]: boolean[] } = {
    '1': [
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
    ],
    '2': [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
    ],
    '3': [
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
    ],
    '4': [
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
    ],
    '5': [
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
    ],
    '6': [
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
    ],
    '7': [
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
    ],
    '8': [
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
    ],
    '9': [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
    ],
    '10': [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
    ],
    '11': [
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
    ],
}
