export enum ITEM_TYPE {
    GOOD = 1,
    ARMOR,
    WEAPON,
}

export interface Item {
    name: string
    cost: number
    weight: number
    description: string
    proficiency?: number
    encumbrance?: number
    damage_type?: number
    damage?: number
    critical?: number
    critical_modifier?: number
    range_increment?: number
    armor_bonus?: number
    max_dex_bonus?: number
    penalty?: number
    spell_failure?: number
}

export const ITEMS: {
    [ITEM_TYPE.GOOD]: { [k: string]: Item }
    [ITEM_TYPE.ARMOR]: { [k: string]: Item }
    [ITEM_TYPE.WEAPON]: { [k: string]: Item }
} = {
    [ITEM_TYPE.GOOD]: {
        '1': {
            name: 'Caltrops',
            cost: 1,
            weight: 2,
            description:
                'A caltrop is a four-pronged iron spike crafted so that one prong faces up no matter how the caltrop comes to rest. You scatter caltrops on the ground in the hope that your enemies step on them or are at least forced to slow down to avoid them. One 2-pound bag of caltrops covers an area 5 feet square.',
        },
        '2': {
            name: 'Candle',
            cost: 0.01,
            weight: 0,
            description: 'A candle dimly illuminates a 5-foot radius and burns for 1 hour.',
        },
        '3': {
            name: 'Chain',
            cost: 30,
            weight: 2,
            description: 'Chain has hardness 10 and 5 hit points. It can be burst with a DC 26 Strength check.',
        },
        '4': {
            name: 'Crowbar',
            cost: 2,
            weight: 5,
            description:
                'A crowbar grants a +2 circumstance bonus on Strength checks made for such purposes. If used in combat, treat a crowbar as a one-handed improvised weapon that deals bludgeoning damage equal to that of a club of its size.',
        },
        '5': {
            name: 'Flint and Steel',
            cost: 1,
            weight: 0,
            description:
                'Lighting a torch with flint and steel is a full-round action, and lighting any other fire with them takes at least that long.',
        },
        '6': {
            name: 'Grappling Hook',
            cost: 1,
            weight: 4,
            description:
                'Throwing a grappling hook successfully requires a Use Rope check (DC 10, +2 per 10 feet of distance thrown).',
        },
        '7': {
            name: 'Hammer',
            cost: 0.5,
            weight: 2,
            description:
                'If a hammer is used in combat, treat it as a one-handed improvised weapon that deals bludgeoning damage equal to that of a spiked gauntlet of its size.',
        },
        '8': {
            name: 'Ink',
            cost: 8,
            weight: 0,
            description: 'This is black ink. You can buy ink in other colors, but it costs twice as much.',
        },
        '9': {
            name: 'Jug, Clay',
            cost: 0.03,
            weight: 9,
            description: 'This basic ceramic jug is fitted with a stopper and holds 1 gallon of liquid.',
        },
        '10': {
            name: 'Lamp, Common',
            cost: 0.1,
            weight: 1,
            description:
                'A lamp clearly illuminates a 15-foot radius, provides shadowy illumination out to a 30-foot radius, and burns for 6 hours on a pint of oil. You can carry a lamp in one hand.',
        },
        '11': {
            name: 'Lantern, Bullseye',
            cost: 12,
            weight: 3,
            description:
                'A bullseye lantern provides clear illumination in a 60-foot cone and shadowy illumination in a 120-foot cone. It burns for 6 hours on a pint of oil. You can carry a bullseye lantern in one hand.',
        },
        '12': {
            name: 'Lantern, Hooded',
            cost: 7,
            weight: 2,
            description:
                'A hooded lantern clearly illuminates a 30-foot radius and provides shadowy illumination in a 60-foot radius. It burns for 6 hours on a pint of oil. You can carry a hooded lantern in one hand.',
        },
        '13': {
            name: 'Lock (very simple)',
            cost: 20,
            weight: 1,
            description:
                'The DC to open a lock with the Open Lock skill depends on the locks quality: simple (DC 20), average (DC 25), good (DC 30), or superior (DC 40).',
        },
        '14': {
            name: 'Lock (average)',
            cost: 40,
            weight: 1,
            description:
                'The DC to open a lock with the Open Lock skill depends on the locks quality: simple (DC 20), average (DC 25), good (DC 30), or superior (DC 40).',
        },
        '15': {
            name: 'Lock (good)',
            cost: 80,
            weight: 1,
            description:
                'The DC to open a lock with the Open Lock skill depends on the locks quality: simple (DC 20), average (DC 25), good (DC 30), or superior (DC 40).',
        },
        '16': {
            name: 'Lock (amazing)',
            cost: 150,
            weight: 1,
            description:
                'The DC to open a lock with the Open Lock skill depends on the locks quality: simple (DC 20), average (DC 25), good (DC 30), or superior (DC 40).',
        },
        '17': {
            name: 'Manacles',
            cost: 15,
            weight: 2,
            description:
                'Manacles can bind a Medium creature. A manacled creature can use the Escape Artist skill to slip free (DC 30, or DC 35 for masterwork manacles). Breaking the manacles requires a Strength check (DC 26, or DC 28 for masterwork manacles). Manacles have hardness 10 and 10 hit points',
        },
        '18': {
            name: 'Manacles, masterwork',
            cost: 50,
            weight: 2,
            description:
                'Manacles can bind a Medium creature. A manacled creature can use the Escape Artist skill to slip free (DC 30, or DC 35 for masterwork manacles). Breaking the manacles requires a Strength check (DC 26, or DC 28 for masterwork manacles). Manacles have hardness 10 and 10 hit points',
        },
        '19': {
            name: 'Oil',
            cost: 0.1,
            weight: 1,
            description:
                'A pint of oil burns for 6 hours in a lantern. You can use a flask of oil as a splash weapon. Use the rules for alchemists fire, except that it takes a full round action to prepare a flask with a fuse. Once it is thrown, there is a 50% chance of the flask igniting successfully. You can pour a pint of oil on the ground to cover an area 5 feet square, provided that the surface is smooth. If lit, the oil burns for 2 rounds and deals 1d3 points of fire damage to each creature in the area.',
        },
        '20': {
            name: 'Rope, Hempen',
            cost: 1,
            weight: 10,
            description: 'This rope has 2 hit points and can be burst with a DC 23 Strength check.',
        },
        '21': {
            name: 'Rope, Silk',
            cost: 10,
            weight: 5,
            description:
                'This rope has 4 hit points and can be burst with a DC 24 Strength check. It is so supple that it provides a +2 circumstance bonus on Use Rope checks.',
        },
        '22': {
            name: 'Spyglass',
            cost: 1000,
            weight: 1,
            description: 'Objects viewed through a spyglass are magnified to twice their size.',
        },
        '23': {
            name: 'Torch',
            cost: 0.01,
            weight: 1,
            description:
                'A torch burns for 1 hour, clearly illuminating a 20-foot radius and providing shadowy illumination out to a 40-foot radius. If a torch is used in combat, treat it as a one-handed improvised weapon that deals bludgeoning damage equal to that of a gauntlet of its size, plus 1 point of fire damage.',
        },
        '24': {
            name: 'Vial',
            cost: 1,
            weight: 1,
            description:
                'A vial holds 1 ounce of liquid. The stoppered container usually is no more than 1 inch wide and 3 inches high.',
        },
    },
    [ITEM_TYPE.ARMOR]: {
        '1': {
            name: 'Padded',
            cost: 5,
            proficiency: 1,
            weight: 10,
            armor_bonus: 1,
            max_dex_bonus: 8,
            penalty: 0,
            spell_failure: 5,
            description: '',
        },
        '2': {
            name: 'Leather',
            cost: 10,
            proficiency: 1,
            weight: 15,
            armor_bonus: 2,
            max_dex_bonus: 6,
            penalty: 0,
            spell_failure: 10,
            description: '',
        },
        '3': {
            name: 'Studded leather',
            cost: 25,
            proficiency: 1,
            weight: 20,
            armor_bonus: 3,
            max_dex_bonus: 5,
            penalty: -1,
            spell_failure: 15,
            description: '',
        },
        '4': {
            name: 'Chain shirt',
            cost: 100,
            proficiency: 1,
            weight: 25,
            armor_bonus: 4,
            max_dex_bonus: 4,
            penalty: -2,
            spell_failure: 20,
            description: 'A chain shirt comes with a steel cap.',
        },
        '5': {
            name: 'Hide',
            cost: 15,
            proficiency: 2,
            weight: 25,
            armor_bonus: 3,
            max_dex_bonus: 4,
            penalty: -3,
            spell_failure: 20,
            description: '',
        },
        '6': {
            name: 'Scale mail',
            cost: 50,
            proficiency: 2,
            weight: 30,
            armor_bonus: 4,
            max_dex_bonus: 3,
            penalty: -4,
            spell_failure: 25,
            description: 'The suit includes gauntlets.',
        },
        '7': {
            name: 'Chainmail',
            cost: 150,
            proficiency: 2,
            weight: 40,
            armor_bonus: 5,
            max_dex_bonus: 2,
            penalty: -5,
            spell_failure: 30,
            description: 'The suit includes gauntlets',
        },
        '8': {
            name: 'Breastplate',
            cost: 200,
            proficiency: 2,
            weight: 30,
            armor_bonus: 5,
            max_dex_bonus: 3,
            penalty: -4,
            spell_failure: 25,
            description: 'It comes with a helmet and greaves.',
        },
        '9': {
            name: 'Splint mail',
            cost: 200,
            proficiency: 3,
            weight: 45,
            armor_bonus: 6,
            max_dex_bonus: 0,
            penalty: -7,
            spell_failure: 40,
            description: 'The suit includes gauntlets.',
        },
        '10': {
            name: 'Banded mail',
            cost: 250,
            proficiency: 3,
            weight: 35,
            armor_bonus: 6,
            max_dex_bonus: 1,
            penalty: -6,
            spell_failure: 35,
            description: 'The suit includes gauntlets.',
        },
        '11': {
            name: 'Half-plate',
            cost: 600,
            proficiency: 3,
            weight: 50,
            armor_bonus: 7,
            max_dex_bonus: 0,
            penalty: -7,
            spell_failure: 40,
            description: 'The suit includes gauntlets.',
        },
        '12': {
            name: 'Full plate',
            cost: 1500,
            proficiency: 3,
            weight: 50,
            armor_bonus: 8,
            max_dex_bonus: 1,
            penalty: -6,
            spell_failure: 35,
            description:
                'The suit includes gauntlets, heavy leather boots, a visored helmet, and a thick layer of padding that is worn underneath the armor. Each suit of full plate must be individually fitted to its owner by a master armorsmith, although a captured suit can be resized to fit a new owner at a cost of 200 to 800 (2d4x100) gold pieces.',
        },
        '13': {
            name: 'Buckler',
            cost: 15,
            proficiency: 4,
            weight: 5,
            armor_bonus: 1,
            max_dex_bonus: 8,
            penalty: -1,
            spell_failure: 5,
            description:
                'This small metal shield is worn strapped to your forearm. You can use a bow or crossbow without penalty while carrying it. You can also use your shield arm to wield a weapon (whether you are using an off-hand weapon or using your off hand to help wield a two-handed weapon), but you take a -1 penalty on attack rolls while doing so. This penalty stacks with those that may apply for fighting with your off hand and for fighting with two weapons. In any case, if you use a weapon in your off hand, you dont get the bucklers AC bonus for the rest of the round.',
        },
        '14': {
            name: 'Shield, light wooden',
            cost: 3,
            proficiency: 4,
            weight: 5,
            armor_bonus: 1,
            max_dex_bonus: 8,
            penalty: -1,
            spell_failure: 5,
            description:
                'Wooden and steel shields offer the same basic protection, though they respond differently to special attacks',
        },
        '15': {
            name: 'Shield, light steel',
            cost: 9,
            proficiency: 4,
            weight: 6,
            armor_bonus: 1,
            max_dex_bonus: 8,
            penalty: -1,
            spell_failure: 5,
            description:
                'Wooden and steel shields offer the same basic protection, though they respond differently to special attacks',
        },
        '16': {
            name: 'Shield, heavy wooden',
            cost: 7,
            proficiency: 4,
            weight: 10,
            armor_bonus: 2,
            max_dex_bonus: 8,
            penalty: -2,
            spell_failure: 15,
            description:
                'Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.',
        },
        '17': {
            name: 'Shield, heavy steel',
            cost: 20,
            proficiency: 4,
            weight: 15,
            armor_bonus: 2,
            max_dex_bonus: 8,
            penalty: -2,
            spell_failure: 15,
            description:
                'Wooden and steel shields offer the same basic protection, though they respond differently to special attacks.',
        },
        '18': {
            name: 'Shield, tower',
            cost: 30,
            proficiency: 4,
            weight: 45,
            armor_bonus: 4,
            max_dex_bonus: 2,
            penalty: -10,
            spell_failure: 50,
            description:
                'This massive wooden shield is nearly as tall as you are. In most situations, it provides the indicated shield bonus to your AC. However, you can instead use it as total cover, though you must give up your attacks to do so. The shield does not, however, provide cover against targeted spells; a spellcaster can cast a spell on you by targeting the shield you are holding. You cannot bash with a tower shield, nor can you use your shield hand for anything else.',
        },
    },
    [ITEM_TYPE.WEAPON]: {
        '1': {
            name: 'Gauntlet',
            cost: 2,
            proficiency: 1,
            encumbrance: 1,
            damage_type: 1,
            weight: 1,
            damage: 3,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'This metal glove lets you deal lethal damage rather than nonlethal damage with unarmed strikes. A strike with a gauntlet is otherwise considered an unarmed attack. The cost and weight given are for a single gauntlet. Medium and heavy armors (except breastplate) come with gauntlets.',
        },
        '2': {
            name: 'Dagger',
            cost: 2,
            proficiency: 1,
            encumbrance: 2,
            damage_type: 2,
            weight: 1,
            damage: 4,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description:
                'You get a +2 bonus on Sleight of Hand checks made to conceal a dagger on your body (see the Sleight of Hand skill).',
        },
        '3': {
            name: 'Gauntlet, spiked',
            cost: 5,
            proficiency: 1,
            encumbrance: 2,
            damage_type: 2,
            weight: 1,
            damage: 4,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'Your opponent cannot use a disarm action to disarm you of spiked gauntlets. The cost and weight given are for a single gauntlet. An attack with a spiked gauntlet is considered an armed attack.',
        },
        '4': {
            name: 'Mace, light',
            cost: 5,
            proficiency: 1,
            encumbrance: 2,
            damage_type: 1,
            weight: 4,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '5': {
            name: 'Sickle',
            cost: 6,
            proficiency: 1,
            encumbrance: 2,
            damage_type: 3,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A sickle can be used to make trip attacks. If you are tripped during your own trip attempt, you can drop the sickle to avoid being tripped.',
        },
        '6': {
            name: 'Club',
            cost: 0.1,
            proficiency: 1,
            encumbrance: 3,
            damage_type: 1,
            weight: 3,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '7': {
            name: 'Mace, heavy',
            cost: 12,
            proficiency: 1,
            encumbrance: 3,
            damage_type: 1,
            weight: 8,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '8': {
            name: 'Morningstar',
            cost: 8,
            proficiency: 1,
            encumbrance: 3,
            damage_type: 1,
            weight: 6,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '9': {
            name: 'Shortspear',
            cost: 1,
            proficiency: 1,
            encumbrance: 3,
            damage_type: 2,
            weight: 3,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: 'A shortspear is small enough to wield one-handed. It may also be thrown.',
        },
        '10': {
            name: 'Longspear',
            cost: 5,
            proficiency: 1,
            encumbrance: 4,
            damage_type: 2,
            weight: 9,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A longspear has reach. You can strike opponents 10 feet away with it, but you cant use it against an adjacent foe. If you use a ready action to set a longspear against a charge, you deal double damage on a successful hit against a charging character.',
        },
        '11': {
            name: 'Quarterstaff',
            cost: 0.1,
            proficiency: 1,
            encumbrance: 4,
            damage_type: 1,
            weight: 4,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A quarterstaff is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a quarterstaff in one hand cant use it as a double weapon-only one end of the weapon can be used in any given round.',
        },
        '12': {
            name: 'Spear',
            cost: 2,
            proficiency: 1,
            encumbrance: 4,
            damage_type: 2,
            weight: 6,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '13': {
            name: 'Crossbow, heavy',
            cost: 50,
            proficiency: 1,
            encumbrance: 5,
            damage_type: 2,
            weight: 8,
            damage: 10,
            critical: 2,
            critical_modifier: -1,
            range_increment: 120,
            description:
                'You draw a heavy crossbow back by turning a small winch. Loading a heavy crossbow is a full-round action that provokes attacks of opportunity.',
        },
        '14': {
            name: 'Crossbow, light',
            cost: 35,
            proficiency: 1,
            encumbrance: 5,
            damage_type: 2,
            weight: 4,
            damage: 8,
            critical: 2,
            critical_modifier: -1,
            range_increment: 80,
            description:
                'You draw a light crossbow back by pulling a lever. Loading a light crossbow is a move action that provokes attacks of opportunity.',
        },
        '15': {
            name: 'Dart',
            cost: 0.5,
            proficiency: 1,
            encumbrance: 5,
            damage_type: 2,
            weight: 1,
            damage: 4,
            critical: 2,
            critical_modifier: 0,
            range_increment: 20,
            description: '',
        },
        '16': {
            name: 'Javelin',
            cost: 1,
            proficiency: 1,
            encumbrance: 5,
            damage_type: 2,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 30,
            description:
                'Since it is not designed for melee, you are treated as nonproficient with it and take a -4 penalty on attack rolls if you use a javelin as a melee weapon.',
        },
        '17': {
            name: 'Sling',
            cost: 0.1,
            proficiency: 1,
            encumbrance: 5,
            damage_type: 1,
            weight: 0,
            damage: 4,
            critical: 2,
            critical_modifier: 0,
            range_increment: 50,
            description:
                'Your Strength modifier applies to damage rolls when you use a sling, just as it does for thrown weapons. You can fire, but not load, a sling with one hand. Loading a sling is a move action that requires two hands and provokes attacks of opportunity.',
        },
        '18': {
            name: 'Axe',
            cost: 8,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 3,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '19': {
            name: 'Hammer, light',
            cost: 1,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 1,
            weight: 2,
            damage: 4,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '20': {
            name: 'Handaxe',
            cost: 6,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 3,
            weight: 3,
            damage: 6,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '21': {
            name: 'Kukri',
            cost: 8,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 3,
            weight: 2,
            damage: 4,
            critical: 2,
            critical_modifier: -2,
            range_increment: 0,
            description: '',
        },
        '22': {
            name: 'Pick, light',
            cost: 4,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 2,
            weight: 3,
            damage: 4,
            critical: 4,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '23': {
            name: 'Sap',
            cost: 1,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 1,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '24': {
            name: 'Sword, short',
            cost: 10,
            proficiency: 2,
            encumbrance: 2,
            damage_type: 2,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description: '',
        },
        '25': {
            name: 'Battleaxe',
            cost: 10,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 3,
            weight: 6,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '26': {
            name: 'Flail',
            cost: 8,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 1,
            weight: 5,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'With a flail, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).',
        },
        '27': {
            name: 'Longsword',
            cost: 15,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 3,
            weight: 4,
            damage: 8,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description: '',
        },
        '28': {
            name: 'Pick, heavy',
            cost: 8,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 2,
            weight: 6,
            damage: 6,
            critical: 4,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '29': {
            name: 'Rapier',
            cost: 20,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 2,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: -2,
            range_increment: 0,
            description:
                'You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a rapier sized for you, even though it isnt a light weapon for you. You cant wield a rapier in two hands in order to apply 1.5 times your Strength bonus to damage.',
        },
        '30': {
            name: 'Scimitar',
            cost: 15,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 3,
            weight: 4,
            damage: 6,
            critical: 2,
            critical_modifier: -2,
            range_increment: 0,
            description: '',
        },
        '31': {
            name: 'Trident',
            cost: 15,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 2,
            weight: 4,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'This weapon can be thrown. If you use a ready action to set a trident against a charge, you deal double damage on a successful hit against a charging character.',
        },
        '32': {
            name: 'Warhammer',
            cost: 12,
            proficiency: 2,
            encumbrance: 3,
            damage_type: 1,
            weight: 5,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '33': {
            name: 'Falchion',
            cost: 75,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 8,
            damage: 8,
            critical: 2,
            critical_modifier: -2,
            range_increment: 0,
            description: '',
        },
        '34': {
            name: 'Glaive',
            cost: 8,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 10,
            damage: 10,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A glaive has reach. You can strike opponents 10 feet away with it, but you cant use it against an adjacent foe.',
        },
        '35': {
            name: 'Greataxe',
            cost: 20,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 12,
            damage: 12,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '36': {
            name: 'Greatclub',
            cost: 5,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 1,
            weight: 8,
            damage: 10,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description: '',
        },
        '37': {
            name: 'Flail, heavy',
            cost: 15,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 1,
            weight: 10,
            damage: 10,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description:
                'With a flail, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).',
        },
        '38': {
            name: 'Greatsword',
            cost: 50,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 8,
            damage: 12,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description: '',
        },
        '39': {
            name: 'Guisarme',
            cost: 9,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 12,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A guisarme has reach. You can strike opponents 10 feet away with it, but you cant use it against an adjacent foe.',
        },
        '40': {
            name: 'Halberd',
            cost: 10,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 2,
            weight: 12,
            damage: 10,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'If you use a ready action to set a halberd against a charge, you deal double damage on a successful hit against a charging character.',
        },
        '41': {
            name: 'Lance',
            cost: 10,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 2,
            weight: 10,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A lance deals double damage when used from the back of a charging mount. It has reach, so you can strike opponents 10 feet away with it, but you cant use it against an adjacent foe.',
        },
        '42': {
            name: 'Ranseur',
            cost: 10,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 2,
            weight: 12,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A ranseur has reach. You can strike opponents 10 feet away with it, but you cant use it against an adjacent foe.',
        },
        '43': {
            name: 'Scythe',
            cost: 18,
            proficiency: 2,
            encumbrance: 4,
            damage_type: 3,
            weight: 10,
            damage: 8,
            critical: 4,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A scythe can be used to make trip attacks. If you are tripped during your own trip attempt, you can drop the scythe to avoid being tripped.',
        },
        '44': {
            name: 'Longbow',
            cost: 75,
            proficiency: 2,
            encumbrance: 5,
            damage_type: 2,
            weight: 3,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 100,
            description:
                'You need at least two hands to use a bow, regardless of its size. A longbow is too unwieldy to use while you are mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a longbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite longbow (see below) but not a regular longbow.',
        },
        '45': {
            name: 'Longbow, composite',
            cost: 100,
            proficiency: 2,
            encumbrance: 5,
            damage_type: 2,
            weight: 3,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 110,
            description:
                'You need at least two hands to use a bow, regardless of its size. You can use a composite longbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is less than the strength rating of the composite bow, you cant effectively use it, so you take a -2 penalty on attacks with it. The default composite longbow requires a Strength modifier of +0 or higher to use with proficiency. A composite longbow can be made with a high strength rating to take advantage of an above-average Strength score; this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 100 gp to its cost.',
        },
        '46': {
            name: 'Shortbow',
            cost: 30,
            proficiency: 2,
            encumbrance: 5,
            damage_type: 2,
            weight: 2,
            damage: 6,
            critical: 3,
            critical_modifier: 0,
            range_increment: 60,
            description:
                'You need at least two hands to use a bow, regardless of its size. You can use a shortbow while mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a shortbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite shortbow (see below) but not a regular shortbow.',
        },
        '47': {
            name: 'Shortbow, composite',
            cost: 75,
            proficiency: 2,
            encumbrance: 5,
            damage_type: 2,
            weight: 2,
            damage: 6,
            critical: 3,
            critical_modifier: 0,
            range_increment: 70,
            description:
                'You need at least two hands to use a bow, regardless of its size. You can use a composite shortbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is lower than the strength rating of the composite bow, you cant effectively use it, so you take a -2 penalty on attacks with it. The default composite shortbow requires a Strength modifier of +0 or higher to use with proficiency. A composite shortbow can be made with a high strength rating to take advantage of an above-average Strength score; this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 75 gp to its cost.',
        },
        '48': {
            name: 'Kama',
            cost: 2,
            proficiency: 3,
            encumbrance: 2,
            damage_type: 3,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'The kama is a special monk weapon. This designation gives a monk wielding a kama special options.',
        },
        '49': {
            name: 'Nunchaku',
            cost: 2,
            proficiency: 3,
            encumbrance: 2,
            damage_type: 1,
            weight: 2,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'The nunchaku is a special monk weapon. This designation gives a monk wielding a nunchaku special options. With a nunchaku, you get a +2 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).',
        },
        '50': {
            name: 'Sai',
            cost: 1,
            proficiency: 3,
            encumbrance: 2,
            damage_type: 1,
            weight: 1,
            damage: 4,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'With a sai, you get a +4 bonus on opposed attack rolls made to disarm an enemy (including the roll to avoid being disarmed if such an attempt fails).',
        },
        '51': {
            name: 'Siangham',
            cost: 3,
            proficiency: 3,
            encumbrance: 2,
            damage_type: 2,
            weight: 1,
            damage: 6,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'The siangham is a special monk weapon. This designation gives a monk wielding a siangham special options.',
        },
        '52': {
            name: 'Sword, bastard',
            cost: 35,
            proficiency: 3,
            encumbrance: 3,
            damage_type: 3,
            weight: 6,
            damage: 10,
            critical: 2,
            critical_modifier: -1,
            range_increment: 0,
            description:
                'A bastard sword is too large to use in one hand without special training; thus, it is an exotic weapon. A character can use a bastard sword two-handed as a martial weapon.',
        },
        '53': {
            name: 'Waraxe, dwarven',
            cost: 30,
            proficiency: 3,
            encumbrance: 3,
            damage_type: 3,
            weight: 8,
            damage: 10,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A dwarven waraxe is too large to use in one hand without special training; thus, it is an exotic weapon. A Medium character can use a dwarven waraxe two-handed as a martial weapon, or a Large creature can use it one-handed in the same way. A dwarf treats a dwarven waraxe as a martial weapon even when using it in one hand.',
        },
        '54': {
            name: 'Axe, orc double',
            cost: 60,
            proficiency: 3,
            encumbrance: 4,
            damage_type: 3,
            weight: 15,
            damage: 8,
            critical: 3,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'An orc double axe is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon.',
        },
        '55': {
            name: 'Chain, spiked',
            cost: 25,
            proficiency: 3,
            encumbrance: 4,
            damage_type: 2,
            weight: 10,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A spiked chain has reach, so you can strike opponents 10 feet away with it. In addition, unlike most other weapons with reach, it can be used against an adjacent foe.',
        },
        '56': {
            name: 'Flail, dire',
            cost: 90,
            proficiency: 3,
            encumbrance: 4,
            damage_type: 1,
            weight: 10,
            damage: 8,
            critical: 2,
            critical_modifier: 0,
            range_increment: 0,
            description:
                'A dire flail is a double weapon. You can fight with it as if fighting with two weapons, but if you do, you incur all the normal attack penalties associated with fighting with two weapons, just as if you were using a one-handed weapon and a light weapon. A creature wielding a dire flail in one hand cant use it as a double weapon- only one end of the weapon can be used in any given round.',
        },
        '57': {
            name: 'Crossbow, hand',
            cost: 100,
            proficiency: 3,
            encumbrance: 5,
            damage_type: 2,
            weight: 2,
            damage: 4,
            critical: 2,
            critical_modifier: -1,
            range_increment: 30,
            description:
                'You can draw a hand crossbow back by hand. Loading a hand crossbow is a move action that provokes attacks of opportunity.',
        },
        '58': {
            name: 'Crossbow, repeating heavy',
            cost: 400,
            proficiency: 3,
            encumbrance: 5,
            damage_type: 2,
            weight: 12,
            damage: 10,
            critical: 2,
            critical_modifier: -1,
            range_increment: 120,
            description:
                'The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity.',
        },
        '59': {
            name: 'Crossbow, repeating light',
            cost: 250,
            proficiency: 3,
            encumbrance: 5,
            damage_type: 2,
            weight: 6,
            damage: 8,
            critical: 2,
            critical_modifier: -1,
            range_increment: 80,
            description:
                'The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity.',
        },
    },
}

export const WEAPON_PROFICIENCY = {
    '1': 'Simple',
    '2': 'Martial',
    '3': 'Exotic',
}

export const ARMOR_PROFICIENCY = {
    '1': 'Light',
    '2': 'Medium',
    '3': 'Heavy',
    '4': 'Shields',
}

export const WEAPON_ENCUMBRANCE = {
    '1': 'Unarmed',
    '2': 'Light Melee Weapon',
    '3': 'One-Handed Melee Weapon',
    '4': 'Two-Handed Melee Weapon',
    '5': 'Ranged Weapon',
}

export const WEAPON_DAMAGE_TYPE = {
    '1': 'Bludgeoning',
    '2': 'Piercing',
    '3': 'Slashing',
}
